field: d8a19f7f-5bcc-4035-89a4-c0b3befd9f96
fieldLayouts:
  4c830e39-6813-460b-b225-d6b17d860ea7:
    tabs:
      -
        elements:
          -
            fieldUid: 36c68627-dc00-4d86-a012-7482704054a9
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4dc80d2b-b1ff-47bb-8562-0a6ed9cd2969
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  36c68627-dc00-4d86-a012-7482704054a9:
    contentColumnType: text
    fieldGroup: null
    handle: centredTitle
    instructions: ''
    name: 'Centred Title'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  4dc80d2b-b1ff-47bb-8562-0a6ed9cd2969:
    contentColumnType: text
    fieldGroup: null
    handle: centredCopy
    instructions: ''
    name: 'Centred Copy'
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: centredContent
name: 'Centred Content'
sortOrder: 1
