field: e567b6ab-3855-452b-a337-4c119dac4d62
fieldLayouts:
  a3b39778-708a-4de0-9501-6b1d37108919:
    tabs:
      -
        elements:
          -
            fieldUid: a6f02aa5-ab37-46e2-bbd4-3b56930577d5
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 2f6bf496-df01-42e0-9b77-a764f886813d
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b18e27a7-8264-41c8-9914-70b37afe1e37
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  2f6bf496-df01-42e0-9b77-a764f886813d:
    contentColumnType: string
    fieldGroup: null
    handle: aspectRatio
    instructions: ''
    name: 'Aspect Ratio'
    searchable: true
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - '16:9'
            -
              - value
              - '16:9'
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - '4:3'
            -
              - value
              - '4:3'
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - '3:2'
            -
              - value
              - '3:2'
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  a6f02aa5-ab37-46e2-bbd4-3b56930577d5:
    contentColumnType: string
    fieldGroup: null
    handle: images
    instructions: 'Double-click an image thumbnail to apply a caption to an image.'
    name: Images
    searchable: true
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:101a70a1-d200-4629-91e5-3425a0937c0e'
      defaultUploadLocationSubpath: images
      limit: ''
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: 'Add an image'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      singleUploadLocationSource: 'volume:101a70a1-d200-4629-91e5-3425a0937c0e'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  b18e27a7-8264-41c8-9914-70b37afe1e37:
    contentColumnType: text
    fieldGroup: null
    handle: imagesTitle
    instructions: 'Enter Title'
    name: Title
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: imageCarousel
name: 'Image Carousel'
sortOrder: 4
