fieldLayouts:
  6e08a29d-0e72-41b4-aac3-6b49a25d15eb:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: ''
            label: 'Package Name'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: baf92585-f5fa-4c8f-b0c1-bdf44702738a
            instructions: ''
            label: 'Package Intro'
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 967c78dc-e17a-4909-a832-9f5151b2332c
            instructions: ''
            label: 'Packages Copy'
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e567b6ab-3855-452b-a337-4c119dac4d62
            instructions: ''
            label: 'Package Content'
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f1609569-63ed-461e-a6dd-ef9bd55265cd
            instructions: ''
            label: 'Package Image'
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Package Details'
        sortOrder: 1
handle: packages
hasTitleField: true
name: Packages
section: 0d7d6141-cec6-4acc-9665-0f722f1518f5
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
