contentColumnType: string
fieldGroup: 911477c7-3c92-407b-a9a9-e69ccb74eabb
handle: cards
instructions: ''
name: Cards
searchable: true
settings:
  contentTable: '{{%matrixcontent_cards}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
