contentColumnType: string
fieldGroup: 911477c7-3c92-407b-a9a9-e69ccb74eabb
handle: centredContent
instructions: ''
name: 'Centred Content'
searchable: false
settings:
  contentTable: '{{%matrixcontent_centredcontent}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
