enableVersioning: true
handle: packages
name: Packages
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  f3400d6f-0f33-4cef-9521-f8f6620399ec:
    enabledByDefault: true
    hasUrls: true
    template: _private/packages
    uriFormat: 'packages/{slug}'
type: channel
